name: Build and Release Android APK

on:
      push:
            tags:
                  - "v*"
      workflow_dispatch:
            inputs:
                  version:
                        description: "Version tag (e.g., v1.0.0)"
                        required: true
                        default: "v1.0.0"

permissions:
      contents: write

jobs:
      build:
            runs-on: ubuntu-latest

            steps:
                  - name: Checkout repository
                    uses: actions/checkout@v4

                  - name: Setup Node.js
                    uses: actions/setup-node@v4
                    with:
                          node-version: "18"
                          cache: "npm"

                  - name: Setup Java
                    uses: actions/setup-java@v4
                    with:
                          distribution: "temurin"
                          java-version: "17"

                  - name: Setup Android SDK
                    uses: android-actions/setup-android@v3

                  - name: Install dependencies
                    run: npm ci

                  - name: Install Expo CLI
                    run: npm install -g @expo/cli@latest

                  - name: Create .env file
                    run: |
                          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
                          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env

                  - name: Prebuild Android
                    run: npx expo prebuild --platform android --clean

                  - name: Build Android APK
                    run: |
                          cd android
                          ./gradlew assembleRelease

                  - name: Get version
                    id: get_version
                    run: |
                          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
                            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
                          else
                            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
                          fi

                  - name: Create Release
                    id: create_release
                    uses: softprops/action-gh-release@v1
                    with:
                          tag_name: ${{ steps.get_version.outputs.version }}
                          name: Koperasi Fatihul Barokah ${{ steps.get_version.outputs.version }}
                          body: |
                                ## Changes in this Release
                                - Production build of Koperasi Fatihul Barokah mobile app
                                - Built with Expo SDK 52
                                - Android APK ready for installation

                                ## Installation
                                1. Download the APK file below
                                2. Enable "Install from unknown sources" in your Android settings
                                3. Install the APK on your device
                          draft: false
                          prerelease: false
                          files: |
                                android/app/build/outputs/apk/release/app-release.apk
                    env:
                          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
